"""Unit tests for backend/parsers.py"""

import sys
from pathlib import Path
import io
import pytest

# Allow importing the backend package from the project root
sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.parsers import detect_provider, parse_dna_file, ParseError


# ---------------------------------------------------------------------------
# detect_provider
# ---------------------------------------------------------------------------

class TestDetectProvider:
    def test_ancestrydna_header(self):
        headers = ["# AncestryDNA raw data"]
        col    = "rsid\tchromosome\tposition\tallele1\tallele2"
        assert detect_provider(headers, col) == "ancestrydna"

    def test_23andme_header(self):
        headers = ["# This data file generated by 23andMe"]
        col    = "# rsid\tchromosome\tposition\tgenotype"
        assert detect_provider(headers, col) == "23andme"

    def test_myheritage_header(self):
        headers = ["# MyHeritage DNA raw data"]
        col    = "rsid\tchromosome\tposition\tgenotype"
        assert detect_provider(headers, col) == "myheritage"

    def test_ftdna_header(self):
        headers = ["# FamilyTreeDNA raw data export"]
        col    = "RSID\tCHROMOSOME\tPOSITION\tRESULT"
        assert detect_provider(headers, col) == "ftdna"

    def test_livingdna_header(self):
        headers = ["# LivingDNA raw data"]
        col    = "rsid\tchromosome\tposition\tgenotype"
        assert detect_provider(headers, col) == "livingdna"

    def test_column_fallback_ancestrydna(self):
        """No provider header; detect from allele1/allele2 columns."""
        assert detect_provider([], "rsid\tchromosome\tposition\tallele1\tallele2") == "ancestrydna"

    def test_column_fallback_23andme(self):
        assert detect_provider([], "rsid\tchromosome\tposition\tgenotype") == "23andme"

    def test_column_fallback_ftdna(self):
        assert detect_provider([], "RSID\tCHROMOSOME\tPOSITION\tRESULT") == "ftdna"

    def test_generic_fallback(self):
        assert detect_provider([], "id\tchr\tpos\tdata") == "generic"


# ---------------------------------------------------------------------------
# Minimal in-memory DNA file content helpers
# ---------------------------------------------------------------------------

_ANCESTRYDNA_CONTENT = """\
# AncestryDNA raw data download
# This file was generated by AncestryDNA at: Wed Jun 24 12:00:00 2026
#
# rsid\tchromosome\tposition\tallele1\tallele2
rs1801133\t1\t11856378\tA\tA
rs4680\t22\t19951271\tA\tG
rs671\t12\t111803962\tG\tG
rs1051730\t15\t78806023\tT\tT
rs00000_invalid\t1\t999\tN\tN
"""

_23ANDME_CONTENT = """\
# This data file generated by 23andMe at: Wed Jun 24 12:00:00 2026
#
# rsid\tchromosome\tposition\tgenotype
rs1801133\t1\t11856378\tAA
rs4680\t22\t19951271\tAG
rs671\t12\t111803962\tGG
rs1051730\t15\t78806023\tTT
"""


def _write_tmp(tmp_path, filename, content):
    p = tmp_path / filename
    p.write_text(content, encoding="utf-8")
    return str(p)


# ---------------------------------------------------------------------------
# parse_dna_file — AncestryDNA
# parse_dna_file returns: {'provider': str, 'snp_count': int, 'snps': list[dict]}
# ---------------------------------------------------------------------------

class TestParseAncestryDNA:
    def test_returns_dict_with_snps_key(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        assert isinstance(result, dict)
        assert "snps" in result
        assert isinstance(result["snps"], list)

    def test_provider_detected(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        assert result.get("provider") == "ancestrydna"

    def test_snps_non_empty(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        assert len(result["snps"]) > 0

    def test_rsid_in_snps(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        rsids = [r["rsid"] for r in result["snps"]]
        assert "rs4680" in rsids

    def test_alleles_present(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        row = next(r for r in result["snps"] if r["rsid"] == "rs4680")
        assert row["allele1"] == "A"
        assert row["allele2"] == "G"

    def test_chromosome_and_position(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        row = next(r for r in result["snps"] if r["rsid"] == "rs4680")
        assert row["chromosome"] == "22"
        assert str(row["position"]) == "19951271"

    def test_snp_count_matches_snps_length(self, tmp_path):
        path = _write_tmp(tmp_path, "ancestry.txt", _ANCESTRYDNA_CONTENT)
        result = parse_dna_file(path)
        assert result["snp_count"] == len(result["snps"])


# ---------------------------------------------------------------------------
# parse_dna_file — 23andMe
# ---------------------------------------------------------------------------

class TestParse23andMe:
    def test_returns_dict_with_snps_key(self, tmp_path):
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        assert isinstance(result, dict)
        assert "snps" in result

    def test_provider_detected(self, tmp_path):
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        assert result.get("provider") == "23andme"

    def test_snps_non_empty(self, tmp_path):
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        assert len(result["snps"]) > 0

    def test_genotype_split(self, tmp_path):
        """23andMe 'AG' genotype column should split into allele1=A, allele2=G."""
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        row = next(r for r in result["snps"] if r["rsid"] == "rs4680")
        assert row["allele1"] == "A"
        assert row["allele2"] == "G"

    def test_homozygous_split(self, tmp_path):
        """23andMe 'GG' should split into allele1=G, allele2=G."""
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        row = next(r for r in result["snps"] if r["rsid"] == "rs671")
        assert row["allele1"] == "G"
        assert row["allele2"] == "G"

    def test_snp_count_matches_snps_length(self, tmp_path):
        path = _write_tmp(tmp_path, "23andme.txt", _23ANDME_CONTENT)
        result = parse_dna_file(path)
        assert result["snp_count"] == len(result["snps"])


# ---------------------------------------------------------------------------
# ParseError
# ---------------------------------------------------------------------------

class TestParseError:
    def test_nonexistent_file_raises(self, tmp_path):
        with pytest.raises((ParseError, FileNotFoundError)):
            parse_dna_file(str(tmp_path / "does_not_exist.txt"))

    def test_empty_file_raises(self, tmp_path):
        path = _write_tmp(tmp_path, "empty.txt", "")
        with pytest.raises((ParseError, Exception)):
            parse_dna_file(path)
